(() => {
  'use strict';
  const key='growthiq-domain-expert-requests-v1';
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let requests=[],draft={},message='',persisted=true;
  try{const saved=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(saved))requests=saved.filter(r=>r&&typeof r.id==='string'&&typeof r.subject==='string'&&typeof r.created==='string'&&!isNaN(Date.parse(r.created))).map(r=>({...r,details:String(r.details||''),domain:String(r.domain||''),email:String(r.email||''),region:String(r.region||'')}));}catch{persisted=false}
  const date=value=>new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
  const field=(name,label,placeholder,type='text',optional=false)=>`<div class="field"><label for="expert-${name}">${label}${optional?'<span class="expert-optional">Optional</span>':''}</label><input id="expert-${name}" name="${name}" type="${type}" ${optional?'':'required'} maxlength="${name==='subject'?160:254}" value="${escape(draft[name]||'')}" placeholder="${placeholder}" ${name==='email'?'autocomplete="email"':''} aria-describedby="expert-${name}-error"><p id="expert-${name}-error" class="field-error" hidden></p></div>`;
  function history(){return `<section id="expert-history" class="expert-history" aria-labelledby="expert-history-title"><div class="expert-history-head"><div><h2 id="expert-history-title" tabindex="-1">Request history <span>${requests.length}</span></h2><p>Saved in this browser. Select a request to review its details.</p></div></div>${requests.length?requests.map(r=>`<details class="expert-request" ${message&&r.id===requests[0].id?'open':''}><summary><span class="expert-request-title"><strong>${escape(r.subject)}</strong><span><time datetime="${escape(r.created)}">${escape(date(r.created))}</time></span></span><span class="expert-request-status">Saved locally</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 5 7 7-7 7"/></svg></summary><div class="expert-request-detail"><dl><div><dt>Request ID</dt><dd>${escape(r.id)}</dd></div><div><dt>Reply email</dt><dd>${escape(r.email)}</dd></div>${r.region?`<div><dt>Market or geography</dt><dd>${escape(r.region)}</dd></div>`:''}</dl><h3>Your question and context</h3><p>${escape(r.details)}</p><p class="expert-local-note">Preview request only. No expert has been contacted.</p></div></details>`).join(''):`<div class="expert-empty"><h3>No requests yet</h3><p>Your requests will appear here after you submit the form above.</p></div>`}</section>`}
  function view(){return `<div class="expert-page"><div class="expert-layout"><section class="expert-form-panel" aria-labelledby="expert-form-title"><div class="expert-form-heading"><h2 id="expert-form-title">What would you like an expert’s perspective on?</h2><p>Share your question and the business decision behind it.</p></div><div id="expert-confirmation" role="status" tabindex="-1" ${message?'':'hidden'}>${message?`<strong>Request saved to your history</strong><p>${escape(message)}</p>`:''}</div><form id="domain-expert-form" novalidate>${field('subject','Request title','A short description of what you need')}${field('region','Market or geography','e.g. Europe', 'text',true)}<div class="field"><label for="expert-details">Your question and context</label><textarea id="expert-details" name="details" rows="5" maxlength="5000" required placeholder="What are you trying to understand or decide? Include the specific questions you would like to discuss." aria-describedby="expert-details-hint expert-details-error">${escape(draft.details||'')}</textarea><p class="expert-hint" id="expert-details-hint">Include your objective, relevant background and any timing needs.</p><p class="field-error" id="expert-details-error" hidden></p></div>${field('email','Reply email','you@company.com','email')}<div class="expert-submit"><button type="submit" class="btn primary">Submit request <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6"/></svg></button><p>Design preview: saves locally. No request is sent.</p></div><p class="field-error" id="expert-storage-error" role="status" ${persisted?'hidden':''}>Browser storage is unavailable. Requests stay available only while this page is open.</p></form></section><aside class="expert-guide"><h2>Bring the question.<br>Add expert judgment.</h2><p>Ask for a domain expert’s perspective on a market, an industry or a business challenge.</p><div class="expert-guide-note"><h3>A useful brief includes</h3><ul><li>The decision you need to make</li><li>The expertise or market you want to explore</li><li>The questions you want to discuss</li></ul></div><a href="#ask">Prefer to explore with AI? Ask GrowthIQ <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6"/></svg></a></aside></div>${history()}</div>`}
  window.GROWTHIQ_EXPERT={view};
  document.addEventListener('click',event=>{if(event.target.closest('[data-expert-history]')){document.getElementById('expert-history').scrollIntoView({block:'start'});document.getElementById('expert-history-title').focus()}});
  document.addEventListener('input',event=>{if(event.target.form?.id==='domain-expert-form'){draft[event.target.name]=event.target.value;const error=document.getElementById('expert-'+event.target.name+'-error');if(error){error.hidden=true;event.target.removeAttribute('aria-invalid')}}});
  document.addEventListener('submit',event=>{
    if(event.target.id!=='domain-expert-form')return;
    event.preventDefault();const form=event.target;let first;
    for(const name of ['subject','details','email']){const input=form.elements[name],error=document.getElementById('expert-'+name+'-error');const invalid=!input.value.trim()||!input.validity.valid;error.hidden=!invalid;input.setAttribute('aria-invalid',String(invalid));if(invalid){error.textContent=name==='email'&&input.value.trim()?'Enter a valid reply email.':'Please complete this field.';first??=input}}
    if(first){first.focus();return}
    const record={id:'EXP-'+crypto.randomUUID().slice(0,8).toUpperCase(),created:new Date().toISOString(),...Object.fromEntries(new FormData(form).entries())};
    for(const name of ['subject','details','email','region'])record[name]=record[name].trim();
    requests.unshift(record);try{localStorage.setItem(key,JSON.stringify(requests));persisted=true}catch{persisted=false}
    draft={};message=persisted?'Your request is saved in this browser. This preview has not sent it to an expert.':'Your request is available for this visit. Browser storage is unavailable, so it will not survive a reload. No expert has been contacted.';
    document.querySelector('.expert-page').outerHTML=view();document.getElementById('expert-confirmation').focus();
  });
})();
