import React,{useState,useEffect,useRef,useMemo} from 'react';
import {createRoot} from 'react-dom/client';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import * as THREE from 'three';

const chapters=[
 {name:'Your business',title:<>Your business.<br/><em>In perspective.</em></>,lead:'Markets, competitors, customers and signals. One connected intelligence workspace.',route:'home',link:'Open your briefing'},
 {name:'What changed',title:<>See the change.<br/><em>Understand why.</em></>,lead:'Bring a business development into focus, together with its relevance to H.B. Fuller.',route:'signals',link:'Explore live signals'},
 {name:'Where to look',title:<>Find the market.<br/><em>Frame the opportunity.</em></>,lead:'Explore the available market context before deciding where to investigate further.',route:'markets',link:'Open market explorer'},
 {name:'Who matters',title:<>Know your peers.<br/><em>See the overlap.</em></>,lead:'Compare the customer segments served by H.B. Fuller and its competitors.',route:'competitors',link:'Open competitor intelligence'},
 {name:'Customer context',title:<>Understand the reach.<br/><em>Keep the context.</em></>,lead:'Connect customer-segment coverage with the existing customer intelligence workspace.',route:'customers',link:'Open customer workspace'},
 {name:'The question',title:<>Ask a better question.<br/><em>Shape the research.</em></>,lead:'Turn the evidence you selected into an editable research question.',route:'ask',link:'Continue in Ask GrowthIQ'},
 {name:'The next decision',title:<>From perspective<br/><em>to a clear brief.</em></>,lead:'Bring your selected context into a strategy brief, ready to refine and review.',route:'studio',link:'Explore Intelligence Studio'}
];
const positions=[[0,0,0],[-4,0,-2.6],[0,0,-4.4],[4,0,-2.6],[4.3,0,2.3],[0,0,4.5],[-4.2,0,2.4]];
const labels=['H.B. Fuller','Signals','Markets','Competitors','Customers','Ask GrowthIQ','Intelligence Studio'];
const A=({back=false})=><svg viewBox="0 0 24 24" aria-hidden="true" style={back?{transform:'rotate(180deg)'}:undefined}><path d="M4 12h15m-6-6 6 6-6 6"/></svg>;
function labelTexture(text,active){const canvas=document.createElement('canvas');canvas.width=640;canvas.height=210;const c=canvas.getContext('2d');c.fillStyle=active?'#183f58':'#132a3c';c.fillRect(0,0,640,210);c.strokeStyle=active?'#93dbf0':'#4a697d';c.lineWidth=3;c.strokeRect(2,2,636,206);c.fillStyle=active?'#c9f4ff':'#d8e5ed';c.textAlign='center';c.font='500 60px "Source Sans 3",sans-serif';c.fillText(text,320,118);const t=new THREE.CanvasTexture(canvas);t.colorSpace=THREE.SRGBColorSpace;return t}
function Landmark({index,active,onChoose}){const sign=useRef();useFrame(({camera})=>{if(sign.current)sign.current.quaternion.copy(camera.quaternion)});const p=positions[index],text=labels[index];const texture=useMemo(()=>labelTexture(text,active),[text,active]);useEffect(()=>()=>texture.dispose(),[texture]);return <group position={p} onClick={e=>{e.stopPropagation();onChoose(index)}}>
 <mesh position={[0,active?.22:0,0]}><cylinderGeometry args={[index===0?1.25:1,index===0?1.3:1.06,.22,6]}/><meshStandardMaterial color={active?'#246780':'#203d50'} metalness={.65} roughness={.3}/></mesh>
 <mesh position={[0,.2,0]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[index===0?1.45:1.14,index===0?1.47:1.16,64]}/><meshBasicMaterial color={active?'#9bdcee':'#4b7891'} side={THREE.DoubleSide}/></mesh>
 <mesh ref={sign} position={[0,.95,0]}><planeGeometry args={[3,.985]}/><meshBasicMaterial map={texture} side={THREE.DoubleSide} toneMapped={false}/></mesh>
 <mesh position={[0,.45,0]}><cylinderGeometry args={[.03,.03,.8,8]}/><meshBasicMaterial color={active?'#b1edff':'#64879b'}/></mesh>
 </group>}
function Path({index,active}){const geo=useMemo(()=>{const p=positions[index];return new THREE.BufferGeometry().setFromPoints(new THREE.CatmullRomCurve3([new THREE.Vector3(0,.1,0),new THREE.Vector3(p[0]*.42,.11,p[2]*.3),new THREE.Vector3(p[0],.1,p[2])]).getPoints(40))},[index]);useEffect(()=>()=>geo.dispose(),[geo]);return <line geometry={geo}><lineBasicMaterial color={active?'#b2eeff':'#49677c'} transparent opacity={active?1:.85}/></line>}
function CameraJourney({chapter,still}){const {camera,invalidate,size}=useThree();const look=useRef(new THREE.Vector3(0,0,0));const destination=useMemo(()=>{const p=positions[chapter],wide=size.width/size.height;const distance=wide<1?1.65:1;return chapter?{eye:new THREE.Vector3(p[0]+1.2*distance,2.1*distance,p[2]+3.2*distance),look:new THREE.Vector3(p[0],.65,p[2])}:{eye:new THREE.Vector3(3.2*distance,5.7*distance,8.5*distance),look:new THREE.Vector3(0,0,0)}},[chapter,size.width,size.height]);useEffect(()=>invalidate(),[destination,still]);useFrame((_,delta)=>{const k=still?1:1-Math.exp(-Math.min(delta,.05)*4);camera.position.lerp(destination.eye,k);look.current.lerp(destination.look,k);camera.lookAt(look.current);if(camera.position.distanceTo(destination.eye)>.005||look.current.distanceTo(destination.look)>.005)invalidate()});return null}
class Boundary extends React.Component{constructor(p){super(p);this.state={failed:false}}static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?this.props.fallback:this.props.children}}
function Landscape({chapter,still,onChoose}){const [ready]=useState(()=>{try{const c=document.createElement('canvas'),gl=c.getContext('webgl2');if(!gl)return false;gl.getExtension('WEBGL_lose_context')?.loseContext();return true}catch{return false}});const fallback=<div className="gd-map-fallback">{labels.map((l,i)=><span className={i===chapter?'selected':''} key={l}>{l}</span>)}</div>;return <div className="gd-landscape" aria-hidden="true">{ready?<Boundary fallback={fallback}><Canvas frameloop="demand" camera={{position:[6,9,13],fov:43}} dpr={[1,1.5]} gl={{alpha:true,antialias:true,powerPreference:'low-power'}} fallback={fallback}><CameraJourney chapter={chapter} still={still}/><ambientLight intensity={2}/><directionalLight position={[4,9,7]} intensity={3} color="#bbdcff"/><pointLight position={[-5,4,0]} intensity={30} color="#6ea3be"/>{positions.map((_,i)=><React.Fragment key={i}>{i>0&&<Path index={i} active={chapter===i}/>}<Landmark index={i} active={chapter===i} onChoose={onChoose}/></React.Fragment>)}<mesh rotation={[-Math.PI/2,0,0]} position={[0,-.2,0]}><ringGeometry args={[6.2,6.215,120]}/><meshBasicMaterial color="#314c61" side={THREE.DoubleSide}/></mesh><mesh rotation={[-Math.PI/2,0,0]} position={[0,-.21,0]}><ringGeometry args={[7.2,7.21,120]}/><meshBasicMaterial color="#203b4e" side={THREE.DoubleSide}/></mesh></Canvas></Boundary>:fallback}</div>}
function Demo({session,data,markets,segments,tasks,onExplore,onBrief}){
 const [chapter,setChapter]=useState(session.chapter??0),[signal,setSignal]=useState(session.signal??2),[market,setMarket]=useState(session.market??2),[peer,setPeer]=useState(session.peer??1),[segment,setSegment]=useState(session.segment??0),[question,setQuestion]=useState(session.question??null),[paused,setPaused]=useState(false),[help,setHelp]=useState(false),[message,setMessage]=useState(''),[full,setFull]=useState(false),[reduced,setReduced]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches);
 const root=useRef(),heading=useRef();const s=data.signals[signal],m=markets[market],p=data.coverage[peer];
 const evidence=`Selected signal: ${s.title}\nRelevance to H.B. Fuller: ${s.relevance}\n\nSelected market: ${m[0]}\nCaptured CAGR over the next five years: ${m[1]}%. Captured TAM: USD ${m[2]} B.\n\nSelected peer: ${p.name}\nCustomer segment: ${segments[segment]}\nCaptured coverage — H.B. Fuller: ${data.coverage[0].values[segment]}; ${p.name}: ${p.values[segment]}.\n\nSelections are research context; no causal relationship between these records has been inferred.`;
 const draftQuestion=question??`What should H.B. Fuller investigate about ${m[0]}?`;
 useEffect(()=>{Object.assign(session,{chapter,signal,market,peer,segment,question})},[chapter,signal,market,peer,segment,question]);
 useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)'),update=()=>setReduced(mq.matches);mq.addEventListener('change',update);const fs=()=>setFull(Boolean(document.fullscreenElement));document.addEventListener('fullscreenchange',fs);return()=>{mq.removeEventListener('change',update);document.removeEventListener('fullscreenchange',fs)}},[]);
 const go=next=>{setChapter(Math.max(0,Math.min(6,next)));setMessage('')};
 useEffect(()=>{root.current?.querySelector('.gd-stage')?.scrollTo({top:0});if(matchMedia('(max-width:767px)').matches)root.current?.scrollIntoView({block:'start',behavior:'instant'});heading.current?.focus({preventScroll:true})},[chapter]);
 useEffect(()=>{const handler=e=>{if(e.altKey||e.ctrlKey||e.metaKey||e.shiftKey||e.target.closest('input,textarea,select,[contenteditable="true"]'))return;if(['ArrowRight','PageDown'].includes(e.key)){e.preventDefault();go(chapter+1)}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(chapter-1)}if(e.key==='Escape')setHelp(false)};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler)},[chapter]);
 const fullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(root.current.requestFullscreen)await root.current.requestFullscreen();else throw Error();}catch{setMessage('Full screen is unavailable here. The presentation remains usable in this window.')}};
 const requireQuestion=()=>{if(draftQuestion.trim())return true;go(5);setMessage('Enter a research question before continuing.');return false};
 const explore=route=>{if(route==='ask'&&!requireQuestion())return;onExplore(route,{signal,market,peer,question:draftQuestion+'\n\n'+evidence})};
 const chapterMeta=chapters[chapter];
 return <div ref={root} className="gd-app" data-still={paused||reduced}>
 <header className="gd-header"><a href="#home" className="gd-brand">Growth<span>IQ</span><span className="gd-live">Live</span></a><span className="gd-workspace">H.B. Fuller</span><div className="gd-presenter-tools"><button aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?'Resume motion':'Pause motion'}</button><button onClick={fullscreen}>{full?'Exit full screen':'Full screen'}</button><button onClick={()=>setHelp(!help)} aria-expanded={help}>Presenter controls</button><a href="#keynote">Keynote <A/></a><a href="#home">Exit demo <A/></a></div></header>
 {help&&<aside className="gd-help"><strong>Presenter controls</strong><p>Use Right / Left or Page Down / Page Up to move between chapters. Chapter buttons jump directly. Motion can be paused. Typing in a field leaves keyboard shortcuts inactive.</p><button onClick={()=>{go(0);setHelp(false)}}>Restart story</button><a href="#support">Support</a><button onClick={()=>setHelp(false)}>Close controls</button></aside>}
 <nav className="gd-chapters" aria-label="Presentation chapters">{chapters.map((c,i)=><button key={c.name} aria-current={chapter===i?'step':undefined} onClick={()=>go(i)}><span>{String(i+1).padStart(2,'0')}</span>{c.name}</button>)}</nav>
 <main className={'gd-stage gd-chapter-'+chapter}>
 <div className="gd-narrative"><h2 ref={heading} tabIndex={-1} key={chapter}>{chapterMeta.title}</h2><p>{chapterMeta.lead}</p><div className="gd-context"><span>H.B. Fuller intelligence</span><span>Captured product records · September 2026</span></div>{chapter!==6&&chapter!==5&&<button className="gd-workflow-link" onClick={()=>explore(chapterMeta.route)}>{chapterMeta.link} <A/></button>}{chapter===3&&<button className="gd-workflow-link" onClick={()=>explore('benchmark')}>View financial benchmarking <A/></button>}{chapter===1&&<button className="gd-workflow-link" onClick={()=>explore('home')}>Read in your briefing <A/></button>}{chapter===6&&<button className="gd-workflow-link" onClick={()=>explore('studio')}>Explore all Studio capabilities <A/></button>}</div>
 <div className="gd-evidence"><div className="gd-spatial-context"><Landscape chapter={chapter} still={paused||reduced} onChoose={go}/><p>Product landscape · use the chapters to explore</p></div>
 <div className="gd-chapter-content" key={chapter}>
 {chapter===0&&<div className="gd-overview"><p>Choose a perspective.</p><div>{chapters.slice(1,6).map((c,i)=><button key={c.name} onClick={()=>go(i+1)}>{labels[i+1]} <A/></button>)}</div><span>Your selections stay with the story.</span></div>}
 {chapter===1&&<section className="gd-signal"><label className="gd-select-label">Select a captured signal<select value={signal} onChange={e=>setSignal(Number(e.target.value))}>{data.signals.map((v,i)=><option key={v.title} value={i}>{v.title}</option>)}</select></label><div className="gd-record-meta"><span>{s.category}</span><span>{s.age} ago in captured record</span></div><h3>{s.title}</h3><p>{s.summary}</p><details><summary>Why it matters to H.B. Fuller</summary><p>{s.relevance}</p></details></section>}
 {chapter===2&&<section className="gd-market"><label className="gd-select-label">Select a market<select value={market} onChange={e=>setMarket(Number(e.target.value))}>{markets.map((v,i)=><option key={v[0]} value={i}>{v[0]}</option>)}</select></label><h3>{m[0]}</h3><div className="gd-market-figures"><div><strong>{m[1]}<small>%</small></strong><span>Captured CAGR</span><p>Over the next five years</p></div><div><strong>{m[2]}<small>B</small></strong><span>Captured TAM · USD</span><p>As recorded in market explorer</p></div></div><p className="gd-evidence-note">Figures reproduce the existing market record. No new forecast is calculated.</p></section>}
 {chapter===3&&<section className="gd-competition"><label className="gd-select-label">Compare with<select value={peer} onChange={e=>setPeer(Number(e.target.value))}>{data.coverage.slice(1).map((v,i)=><option key={v.name} value={i+1}>{v.name}</option>)}</select></label><h3>Customer-segment coverage</h3><table><thead><tr><th>Segment</th><th>H.B. Fuller</th><th>{p.name}</th></tr></thead><tbody>{segments.slice(0,4).map((v,i)=><tr key={v}><th scope="row">{v}</th><td>{data.coverage[0].values[i]}</td><td className={p.values[i]==='No'?'gd-gap':''}>{p.values[i]}</td></tr>)}</tbody></table><p className="gd-evidence-note">Showing four of {segments.length} captured segments. Open competitor intelligence for the full comparison.</p></section>}
 {chapter===4&&<section className="gd-customers"><label className="gd-select-label">Customer segment<select value={segment} onChange={e=>setSegment(Number(e.target.value))}>{segments.map((v,i)=><option key={v} value={i}>{v}</option>)}</select></label><h3>{segments[segment]}</h3><div className="gd-coverage-pair"><div><span>H.B. Fuller</span><strong>{data.coverage[0].values[segment]}</strong></div><div><span>{p.name}</span><strong>{p.values[segment]}</strong></div></div><p>Captured customer-segment coverage from the competitor explorer.</p><div className="gd-access"><strong>Continue in SalesPlay</strong><p>Customer and account details remain in the existing access-controlled customer workspace.</p></div></section>}
 {chapter===5&&<section className="gd-research"><label htmlFor="gd-question">Your research question</label><textarea id="gd-question" value={draftQuestion} onChange={e=>setQuestion(e.target.value)} rows={3}/><div className="gd-selected-context"><span>Selected context</span><p>{m[0]}</p><p>{p.name} · {segments[segment]}</p><details><summary>Selected signal & evidence</summary><p className="gd-preformatted">{evidence}</p></details></div><button className="gd-primary" onClick={()=>explore('ask')}>Continue in Ask GrowthIQ <A/></button><p className="gd-evidence-note">Opens an editable question with this context. No research answer is generated in the demo.</p></section>}
 {chapter===6&&<section className="gd-decision"><span className="gd-format">Strategy brief · PowerPoint presentation</span><h3>{draftQuestion}</h3><div className="gd-decision-scope">{tasks.find(t=>t.id==='strategy-brief').outline.map(x=><div key={x}><span>{x}</span><A/></div>)}</div><details><summary>Review the context you’ll carry forward</summary><p className="gd-preformatted">{evidence}</p></details><button className="gd-primary" onClick={()=>{if(requireQuestion())onBrief({subject:draftQuestion,context:evidence})}}>Prepare this strategy brief <A/></button><p className="gd-evidence-note">This is the capability’s scope, not a generated result. The next step opens the existing brief workspace.</p></section>}
 </div></div>
 </main>
 {message&&<p role="status" className="gd-message">{message}</p>}
 <footer className="gd-footer"><div><span>Product presentation</span><small>Existing data · frontend preview</small></div><div className="gd-progress" aria-label={'Chapter '+(chapter+1)+' of 7'}>{chapters.map((c,i)=><span key={c.name} className={i<=chapter?'complete':''}/>)}</div><div className="gd-step-controls"><button disabled={chapter===0} onClick={()=>go(chapter-1)} aria-label="Previous chapter"><A back/></button><button className="gd-next" onClick={()=>go(chapter===6?0:chapter+1)}>{chapter===6?'Restart story':chapter===0?'Begin the story':chapters[chapter+1].name}<A/></button></div></footer>
 </div>
}
export function mount(element,props){const root=createRoot(element);root.render(<Boundary fallback={<div className="spatial-loading"><h2>Continue in the product workspace</h2><p>The demo encountered a problem. Your saved briefs remain available.</p><a href="#home">Open your briefing</a></div>}><Demo {...props}/></Boundary>);return()=>root.unmount()}
