// Scenario content from the user-provided Ostrel explainer. These are not live records.
export const evidence = {
  markets: {title:'The world around Ostrel', time:'00:25–00:45', lens:'Markets', text:'The explainer places Ostrel inside a network of adjacent markets: electric vehicles, battery packs, wind energy, heat pumps and chip packaging.', implication:'A coatings business can discover new needs by looking beyond its own market.'},
  battery: {title:'A need travels across markets', time:'00:45–01:00', lens:'Markets', text:'In the illustrated chain, larger battery packs create a fire-protection need. That need creates demand for new coatings, reaching Ostrel.', implication:'Investigate battery fire-protection coatings as a possible growth opportunity.'},
  customer: {title:'Talmir’s business is changing', time:'01:15–01:35', lens:'Customers', text:'The example contrasts 22% electric revenue five years ago with 70% electric pipeline today. These are different measures, not a like-for-like growth calculation. The buyer shifts from powertrain purchasing to battery engineering; the specification shifts from corrosion and finish to thermal runaway and fire safety.', implication:'Understand the new battery-pack line and its technical requirements before approaching the customer.'},
  competitor: {title:'Quendra is already moving', time:'01:45–01:55', lens:'Competitors', text:'The fictional competitor Quendra Chemicals is hiring battery engineers, filing patents and building a pilot line.', implication:'Together, these signals suggest a direction worth investigating. They do not establish a market share or a completed commercial win.'},
  synthesis: {title:'Three lenses, one growth question', time:'02:05–02:45', lens:'Connected intelligence', text:'The explainer brings markets, customers and competitors together, then describes applying an AI layer to a company’s specific growth problem.', implication:'This keynote shows a prepared synthesis of the example. It does not run a model, search external sources or generate new research.'},
  action: {title:'From market to conversation', time:'02:45–03:15', lens:'Commercial action', text:'The story connects battery fire-protection coatings to Talmir Motors, its new battery-pack line, its head of battery engineering, and a conversation about passing thermal-runaway tests without adding weight.', implication:'The contact is a fictional role, not an identified person. No outreach is sent.'},
};
export const scenes = [
  {name:'The question', title:['Where will our next','growth come from?'], body:'Meet Ostrel. A coatings company with a much bigger world of opportunity around it.', note:'Start with the question every business asks. Introduce Ostrel as an illustrative coatings company. Let the question sit before advancing.', next:'Begin the story'},
  {name:'One window', title:['The familiar view','only goes so far.'], body:'Our market. Our customers. Our usual competitors. A useful view—with important things outside it.', note:'Ostrel understands coatings. But the next source of demand may start somewhere its usual market view does not reach.', next:'Widen the view'},
  {name:'Connected markets', title:['Your next opportunity','starts elsewhere.'], body:'Electric vehicles. Battery packs. Wind energy. Each creates new needs that can travel across markets.', note:'This is the first reveal. Pause as the network opens. Select a labeled market to bring it into focus. These are illustrative connections, not measured relationships.', next:'Follow the change', evidence:'markets'},
  {name:'Growth travels', title:['A change far away.','A need at your door.'], body:'Larger battery packs need fire protection. Fire protection needs new coatings. That is where the change reaches Ostrel.', note:'Trace the chain from left to right. The movement makes the mechanism visible: an adjacent market changes the need for our product.', next:'Follow the customer', evidence:'battery'},
  {name:'The customer shifts', title:['When their business moves,','your opportunity moves.'], body:'Talmir Motors is moving toward electric vehicles. The buyer, the specification and the moment to act all change with it.', note:'Important: 22% is historical electric revenue; 70% is current electric pipeline. Do not present these as comparable revenue measures. Focus on the changing buyer and requirement.', next:'See who else is moving', evidence:'customer'},
  {name:'Others are moving', title:['Someone else','sees it too.'], body:'Quendra Chemicals is building capabilities around the same emerging need. The window is already opening.', note:'Reveal the three fictional competitor signals together. This creates urgency without inventing a deadline or claiming a commercial win.', next:'Connect the evidence', evidence:'competitor'},
  {name:'Seen together', title:['Three perspectives.','One clearer opportunity.'], body:'Markets reveal the need. Customers reveal the project. Competitors reveal the movement around it.', note:'The value is the combination. Use each lens to inspect what it contributes. All three lead to a single growth question.', next:'Ask the growth question', evidence:'synthesis'},
  {name:'A focused question', title:['Make the question','specific to your growth.'], body:'Carry the market, customer and competitor context into the same investigation.', note:'This is a prepared research example based on the film, not a live AI response. Expand the answer, inspect its supporting story evidence, or open the actual captured GrowthIQ results in a separate tab.', next:'Make it actionable', evidence:'synthesis'},
  {name:'The next conversation', title:['From a world of change','to your next conversation.'], body:'A specific opportunity. A relevant customer. A reason to talk now.', note:'Close on the commercial action. We began with an enormous question and arrived at a concrete customer conversation. The downloadable brief is explicitly illustrative.', next:'Replay the story', evidence:'action'},
];
export const marketNames = ['Ostrel Coatings','Electric vehicles','Battery packs','Wind energy','Heat pumps','Chip packaging','Fire protection','New coatings'];
export const chain = ['Battery packs','Fire protection','New coatings','Ostrel Coatings'];
export const question = 'Where can Ostrel win in battery fire-protection coatings—and who should we speak to first?';
export const brief = `ILLUSTRATIVE GROWTH BRIEF — OSTREL COATINGS\n\nPrepared from MnM_Growth_Explainer_Ostrel.mp4, supplied by the user. All companies and scenario events are fictional. This is not generated research.\n\nQUESTION\n${question}\n\nOPPORTUNITY\nBattery fire-protection coatings.\n\nCUSTOMER AND PROJECT\nTalmir Motors — new battery-pack line.\n\nRELEVANT ROLE\nHead of battery engineering (fictional role; no identified contact).\n\nCONVERSATION\nHow can the new battery-pack line pass thermal-runaway tests without adding weight?\n\nEVIDENCE FROM THE ILLUSTRATION\n${Object.values(evidence).map(e=>`${e.title} (${e.time})\n${e.text}`).join('\n\n')}\n\nNEXT STEP\nValidate the opportunity, technical requirements, project timing and buyer with real research before taking commercial action.\n`;
