import React,{useState,useEffect,useRef,lazy,Suspense} from 'react';
import {createRoot} from 'react-dom/client';
const Scene=lazy(()=>import('./studio-scene.jsx'));
const versions=[['studio','V1','Original'],['studio-next','V2','Guided'],['studio-v3','V3','Spatial map'],['studio-v4','V4','Cinematic demo'],['studio-v5','V5','Editorial']];
const Arrow=({back=false})=><svg viewBox="0 0 24 24" aria-hidden="true" style={back?{transform:'rotate(180deg)'}:undefined}><path d="M4 12h15m-6-6 6 6-6 6"/></svg>;
const Check=()=> <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4 10-10"/></svg>;
function useReduced(){const [value,set]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches);useEffect(()=>{const m=matchMedia('(prefers-reduced-motion: reduce)'),change=()=>set(m.matches);m.addEventListener('change',change);return()=>m.removeEventListener('change',change)},[]);return value}
function VersionLinks({variant}){return <nav className="sv-versions" aria-label="Studio design versions">{versions.map(([id,n,label])=><a key={id} href={'#'+id} aria-current={variant===id?'page':undefined} title={label}>{n}<span>{label}</span></a>)}</nav>}
function Drafts({drafts,tasks,onResume}){const entries=Object.entries(drafts).filter(([id])=>tasks.some(t=>t.id===id));if(!entries.length)return null;return <section className="sv-drafts"><h2>Continue a draft</h2><p>Saved in this browser</p>{entries.map(([id,d])=><button key={id} onClick={()=>onResume(id)}><strong>{d.subject||tasks.find(t=>t.id===id).name}</strong><span>{tasks.find(t=>t.id===id).name}</span><Arrow/></button>)}</section>}
function Scope({task}){return <><span className="sv-format">{task.output}</span><h2>{task.name}</h2><p className="sv-description">{task.description}</p><h3>Deliverable outline</h3><ul className="sv-outline">{task.outline.map(line=><li key={line}><Check/><span>{line}</span></li>)}</ul><details className="sv-about"><summary>About this capability</summary><p>{task.sourceTitle} · {task.metadata}</p></details></>}
function App({variant,session,tasks,goals,drafts,onPrepare,onResume}){
 const [step,setStep]=useState(session.step||0),[subject,setSubject]=useState(session.subject||''),[context,setContext]=useState(session.context||''),[goal,setGoal]=useState(session.goal||''),[selected,setSelected]=useState(session.selected||''),[browse,setBrowse]=useState(session.browse||false),[query,setQuery]=useState(session.query||''),[paused,setPaused]=useState(false),[error,setError]=useState(''),[full,setFull]=useState(false);
 const reduced=useReduced(),cinema=variant==='studio-v4',editorial=variant==='studio-v5';const root=useRef();const stageTitle=useRef();
 useEffect(()=>{Object.assign(session,{step,subject,context,goal,selected,browse,query})},[step,subject,context,goal,selected,browse,query]);
 useEffect(()=>{const update=()=>setFull(Boolean(document.fullscreenElement));document.addEventListener('fullscreenchange',update);return()=>document.removeEventListener('fullscreenchange',update)},[]);
 useEffect(()=>{if(step)stageTitle.current?.focus()},[step]);
 const rows=tasks.filter(t=>(browse||!goal||t.goals.includes(goal))&&(!query||(t.name+' '+t.sourceTitle+' '+t.description).toLowerCase().includes(query.toLowerCase())));
 const task=(step===2?tasks:rows).find(t=>t.id===selected)||rows[0];
 const objective=goals.find(g=>g.id===goal);
 const chooseGoal=id=>{setGoal(id);setSelected('');setBrowse(false);setQuery('');setError('')};
 const proceed=()=>{if(!subject.trim()){setError('Describe a market, company or question to begin.');root.current?.querySelector('[data-sv-subject]')?.focus();return}if(!goal&&!browse){setError('Choose a research objective.');[...root.current.querySelectorAll('[aria-label="Research objectives"] button')].find(button=>button.getClientRects().length)?.focus();return}setError('');setStep(1)};
 const prepare=()=>{if(!subject.trim()){setError('Add a subject for your brief.');setStep(0);return}if(task)onPrepare(task.id,{subject,context})};
 const goalItems=goals.map(g=>({id:g.id,title:g.short,lines:tasks.filter(t=>t.goals.includes(g.id)).slice(0,3).map(t=>t.name)}));
 const idx=Math.max(0,rows.findIndex(t=>t.id===task?.id));const visibleTasks=rows.slice(Math.max(0,Math.min(idx-2,rows.length-5)),Math.max(5,idx+3));
 const sceneItems=step===0?goalItems:visibleTasks.map(t=>({id:t.id,title:t.name,lines:t.outline}));
 const scene=<Suspense fallback={<div className="sv-scene-pending" role="status">Preparing the spatial view…</div>}><Scene items={sceneItems} selected={step===0?goal:task?.id} onSelect={step===0?chooseGoal:setSelected} dark={cinema} reduced={reduced||paused} phase={step}/></Suspense>;
 const briefInput=<div className="sv-brief-field"><label htmlFor={'sv-subject-'+variant}>What are you working on?</label><textarea id={'sv-subject-'+variant} data-sv-subject value={subject} onChange={e=>{setSubject(e.target.value);setError('')}} aria-invalid={error&&!subject.trim()?'true':undefined} aria-describedby={error?'sv-brief-error':undefined} placeholder="A market, company or strategic question…" rows={cinema?2:3}/>{error&&<p id="sv-brief-error" role="alert" className="sv-error">{error}</p>}</div>;
 const objectiveButtons=<div className="sv-objective-controls" role="group" aria-label="Research objectives">{goals.map((g,i)=><button key={g.id} aria-pressed={goal===g.id} onClick={()=>chooseGoal(g.id)}><span className="sv-objective-mark" aria-hidden="true">{i+1}</span><span>{g.short}</span>{goal===g.id?<Check/>:<Arrow/>}</button>)}</div>;
 const search=<div className="sv-search-row"><label><span className="sr-only">Find a deliverable</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a deliverable…"/></label><button className="sv-text-button" onClick={()=>{setBrowse(!browse);setQuery('')}}>{browse?'Use my objective':'All capabilities'}</button></div>;
 const choices=<div className="sv-deliverable-rail" role="group" aria-label="Deliverable choices">{rows.map(t=><button key={t.id} aria-pressed={task?.id===t.id} onClick={()=>setSelected(t.id)}><span>{t.output}</span><strong>{t.name}</strong><Arrow/></button>)}{!rows.length&&<p role="status">No matching deliverables. Change or clear your search.</p>}</div>;
 const footer=<div className="sv-boundary"><span>Brief preparation preview</span><span>Research runs in the existing GrowthIQ setup.</span></div>;
 const motionControl=!editorial&&<button className="sv-motion" aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?'Enable motion':'Pause motion'}</button>;
 const fullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await root.current?.requestFullscreen()}catch{setError('Full screen is unavailable in this browser. You can continue in this view.')}};
 const ready=task&&<div className="sv-ready"><div><h2 ref={stageTitle} tabIndex={-1}>Your brief.<br/>Ready to refine.</h2><p>Review the subject and priorities you’ll take into your workspace.</p>{briefInput}<label className="sv-context-label" htmlFor="sv-context">Context & priorities <span>Optional</span></label><textarea id="sv-context" className="sv-context" value={context} onChange={e=>setContext(e.target.value)} placeholder="What should the research focus on?" rows={4}/><button className="sv-primary" onClick={prepare}>Open brief workspace <Arrow/></button></div><aside><Scope task={task}/></aside></div>;
 return <div ref={root} className={'sv-app '+(cinema?'sv-cinema':editorial?'sv-editorial':'sv-atlas')} data-reduced-motion={reduced||paused?'true':'false'}>
 {cinema?<header className="sv-cinema-header"><a href="#studio-v3" className="sv-cinema-brand">Growth<span>IQ</span><small>Intelligence Studio</small></a><VersionLinks variant={variant}/><button className="sv-text-button" onClick={fullscreen}>{full?'Exit full screen':'Full screen'}</button><a className="sv-exit" href="#studio-v3">Exit demo <Arrow/></a></header>:<div className="sv-topline"><VersionLinks variant={variant}/>{motionControl}</div>}
 {cinema&&<div className="sv-cinema-progress" aria-label="Demo progress">{['The question','The perspective','The brief'].map((label,i)=><button key={label} aria-current={step===i?'step':undefined} disabled={i>step} onClick={()=>setStep(i)}><span>{String(i+1).padStart(2,'0')}</span>{label}</button>)}{motionControl}</div>}
 {!cinema&&<div className="sv-flow-indicator"><span aria-current={step===0?'step':undefined}>Define</span><i/><span aria-current={step===1?'step':undefined}>Explore</span><i/><span aria-current={step===2?'step':undefined}>Prepare</span></div>}
 {step>0&&<button className="sv-back sv-text-button" onClick={()=>{setStep(step-1);setError('')}}><Arrow back/>{step===1?'Edit your brief':'Back to deliverables'}</button>}
 {step===0&&(editorial?<section className="sv-ed-start"><div className="sv-ed-intro"><h2>Decide<br/>what’s <em>next.</em></h2><p>Start with the decision you need to make. Leave with a clearly defined research brief.</p>{briefInput}<button className="sv-primary" onClick={proceed}>Explore deliverables <Arrow/></button></div><div className="sv-ed-objectives" role="group" aria-label="Research objectives"><h3>Choose your direction</h3>{goals.map(g=><button key={g.id} aria-pressed={goal===g.id} onClick={()=>chooseGoal(g.id)}><span>{g.short}</span>{goal===g.id?<Check/>:<Arrow/>}</button>)}<button className="sv-primary sv-mobile-start" onClick={proceed}>Explore deliverables <Arrow/></button><button className="sv-text-button" onClick={()=>{setBrowse(true);setStep(1)}}>Browse all capabilities <Arrow/></button></div></section>:<section className="sv-discover"><div className="sv-intro"><h2>{cinema?<>A question.<br/>A <em>direction.</em></>:<>What’s your<br/><em>next move?</em></>}</h2><p>{cinema?'Bring your next strategic decision into focus.':'Connect the decision you need to make with the research that supports it.'}</p>{briefInput}<div className="sv-mobile-objectives"><h3>Choose your research objective</h3>{objectiveButtons}</div><div className="sv-intro-actions"><button className="sv-primary" onClick={proceed}>{cinema?'Explore the perspective':'Explore deliverables'} <Arrow/></button><button className="sv-text-button" onClick={()=>{setBrowse(true);setStep(1)}}>Browse all capabilities</button></div>{cinema&&<button className="sv-example sv-text-button" onClick={()=>{setSubject('Bioadhesives Market');chooseGoal('growth')}}>Use Bioadhesives Market as an example <Arrow/></button>}</div><div className="sv-map"><div className="sv-map-scene">{scene}</div><p className="sv-map-caption">{objective?objective.name:'Choose a direction to focus your research.'}</p>{objectiveButtons}</div></section>)}
 {step===1&&(editorial?<section className="sv-ed-explore"><div className="sv-ed-brief"><h2 ref={stageTitle} tabIndex={-1}>Your question,<br/><em>in focus.</em></h2><p>{subject||'Choose a deliverable, then define your brief.'}</p>{search}{choices}</div><article className="sv-ed-folio" key={task?.id}>{task?<><Scope task={task}/><button className="sv-primary" onClick={()=>{setSelected(task.id);setStep(2)}}>Shape this brief <Arrow/></button></>:<h2>Find your deliverable</h2>}</article></section>:<section className="sv-explore"><div className="sv-explore-visual"><h2 ref={stageTitle} tabIndex={-1}>{cinema?<>Bring the right<br/><em>perspective.</em></>:<>One question.<br/><em>Different perspectives.</em></>}</h2><p className="sv-subject-summary">{subject||'Explore the available deliverables.'}</p><div className="sv-map-scene">{scene}</div>{search}{choices}</div><article className="sv-scope" key={task?.id}>{task?<><Scope task={task}/><button className="sv-primary" onClick={()=>{setSelected(task.id);setStep(2)}}>Shape this brief <Arrow/></button></>:<h2>Find your deliverable</h2>}</article></section>)}
 {step===2&&ready}
 {step===0&&<Drafts drafts={drafts} tasks={tasks} onResume={onResume}/>}
 {footer}
 </div>;
}
class AppBoundary extends React.Component{constructor(p){super(p);this.state={failed:false}}static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?<div className="spatial-loading"><h2>Continue with Guided Studio</h2><p>The interactive view encountered a problem. Your existing saved briefs remain available.</p><a className="btn primary" href="#studio-next">Open V2</a></div>:this.props.children}}
export function mount(element,props){const root=createRoot(element);root.render(<AppBoundary><App {...props}/></AppBoundary>);return()=>root.unmount()}
