const fs=require('fs'),vm=require('vm'),assert=require('assert');
const root=require('path').resolve(__dirname,'..');const listeners={},registered={},elements=new Map(),store={};
const node=()=>({innerHTML:'',textContent:'',value:'',dataset:{},open:false,checked:false,inert:false,scrollLeft:0,selectionStart:0,classList:{contains:()=>false,add(){},remove(){},toggle:()=>true},setAttribute(){},hasAttribute(){return false},focus(){},setSelectionRange(){},addEventListener(){},close(){this.open=false},showModal(){this.open=true},getBoundingClientRect(){return{left:0,right:100,top:0,bottom:100}},click(){}});
function el(id){if(!elements.has(id))elements.set(id,node());return elements.get(id)}
const ctx={console,setTimeout:()=>0,clearTimeout(){},URL,Blob,location:{hash:'#home',href:'http://127.0.0.1:8770/'},matchMedia:()=>({matches:false,addEventListener(){}}),localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v},document:{documentElement:{dataset:{}},activeElement:null,title:'',getElementById:el,querySelector:s=>el(s),querySelectorAll:()=>[],addEventListener:(k,fn)=>{(registered[k]??=[]).push(fn);listeners[k]=event=>registered[k].forEach(f=>f(event))},createElement:()=>node()},window:{scrollY:0,scrollTo(){},addEventListener(){}},};vm.createContext(ctx);vm.runInContext(fs.readFileSync(root+'/data.js','utf8'),ctx);
vm.runInContext(fs.readFileSync(root+'/studio-data.js','utf8'),ctx);
vm.runInContext(fs.readFileSync(root+'/theme.js','utf8'),ctx);
let code=fs.readFileSync(root+'/app.js','utf8');code=code.replace('  route();\n  window.GROWTHIQ_PREVIEW','  window.__check={state,routeInfo,view,shell,home,marketView,competitors,benchmarking,signals,ask,route,studio,studioWorkspace,studioDraft,studioTask,openStudioTask,reviewStudioBrief,persistStudioDraft,commandResults,studioNext,studioNextState,S};\n  route();\n  window.GROWTHIQ_PREVIEW');vm.runInContext(code,ctx);const t=ctx.window.__check;
const results=[];const test=(name,fn)=>{fn();results.push({name,status:'passed'})};
fs.mkdirSync(root+'/verification',{recursive:true});
for(const route of Object.keys(t.routeInfo)){test('Render '+route,()=>{t.state.route=route;t.state.query='';const html=t.shell();assert.equal((html.match(/<h1>/g)||[]).length,1);assert(!html.includes('undefined'));assert(!html.includes('NaN'));assert(html.includes('id="main"'));fs.writeFileSync(root+'/verification/'+route+'.html',html)})}
function click(dataset={},attrs=[]){const elem=node();elem.dataset=dataset;elem.hasAttribute=k=>attrs.includes(k);listeners.click({target:{closest:()=>elem},preventDefault(){}});return elem}
function change(dataset={},checked=false,attrs=[]){const elem=node();elem.dataset=dataset;elem.checked=checked;elem.hasAttribute=k=>attrs.includes(k);listeners.change({target:elem});}
test('Selecting briefing signal changes reader',()=>{t.state.route='home';click({selectSignal:'2'});assert(t.home().includes('Sika Completes'));assert.equal(t.state.activeSignal,2)});
test('Saving a signal persists locally and filters saved list',()=>{click({pin:'2'});assert(store['growthiq-briefing-pinned'].includes('2'));click({briefFilter:'saved'});const h=t.home();assert(h.includes('data-select-signal="2"'));assert(!h.includes('data-select-signal="0"'))});
test('Unread filter removes marked signal',()=>{t.state.briefFilter='unread';click({read:'2'});const h=t.home();assert(!h.includes('data-select-signal="2"'));assert(h.includes('data-select-signal="0"'))});
test('Empty saved view has recovery',()=>{t.state.briefFilter='saved';click({pin:'2'});assert(t.home().includes('data-brief-reset'));click({},['data-brief-reset']);assert.equal(t.state.briefFilter,'all')});
test('Signal context pre-fills research question without generating',()=>{click({researchSignal:'2'});assert.equal(ctx.location.hash,'ask');assert(t.ask().includes('Sika Completes'));assert(!t.ask().includes('disabled>Start research'))});
test('Research direction inserts an editable question',()=>{click({prompt:'How to Win'});assert(el('research-query').value.includes('competitors'));assert.equal(el('ask-send').disabled,false)});
test('Market search and selection retain query',()=>{t.state.route='markets';t.state.query='Bio';click({market:'Bioadhesives Market'});assert.equal(t.state.activeMarket,2);assert.equal(t.state.query,'Bio');assert(t.marketView().includes('8.6'));assert(!t.marketView().includes('data-market="Bonding'))});
test('Market transfers selected record to research',()=>{click({researchMarket:'2'});assert(t.ask().includes('Bioadhesives'))});
test('Difference comparison changes visible market rows',()=>{t.state.route='competitors';t.state.compare=[0,1];change({},true,['data-differences']);const h=t.competitors();assert(h.includes('Disposable hygiene OEMs'));assert(!h.includes('<th scope="row">CPG &amp; F&amp;B OEMs</th>'))});
test('Identical selected competitors show honest empty difference result',()=>{t.state.compare=[0,2];assert(t.competitors().includes('same footprint'))});
test('One selected competitor shows recovery',()=>{change({compare:'2'},false);assert(t.competitors().includes('Choose at least two companies'))});
test('Financial row selection controls table contents',()=>{t.state.route='benchmark';t.state.financialSelection=[0,1,2,3];change({financial:'1'},false);const h=t.benchmarking();assert(!h.includes('<td><strong style="font-weight:550">Ab Volvo'));assert(h.includes('3 companies'))});
test('Financial metric updates chart',()=>{t.state.chart=true;t.state.metric=5;const h=t.benchmarking();assert(h.includes('Basic EPS comparison'));assert(!h.includes('NaN'));assert(!h.includes('Infinity'))});
test('Live feed filter changes selection to matching record',()=>{t.state.route='signals';t.state.query='Synopsys';const h=t.signals();assert(h.includes('1 signals'));assert(h.includes('data-select-news="0"'));assert(!h.includes('data-select-news="1"'))});
test('Route navigation restores search and scroll context',()=>{t.state.route='markets';t.state.query='Bio';ctx.window.scrollY=230;ctx.location.hash='#ask';t.route();ctx.location.hash='#markets';t.route();assert.equal(t.state.query,'Bio');assert.equal(t.state.savedViews.markets.scroll,230)});
test('New comparison retains original indices after selection changes',()=>{t.state.financialSelection=[2,3];let h=t.benchmarking(true);assert(h.includes('<option value="2">Accenture Plc</option>'));assert(h.includes('<option value="3">Avery Dennison Corporation</option>'));t.state.financialSelection=[];h=t.benchmarking(true);assert(h.includes('<option value="0">3m Company</option>'))});
test('Legacy deep research route opens complete Studio catalog',()=>{t.state.route='deep-research';t.state.query='';t.state.agentFormat='Excel';const h=t.view();assert(h.includes('22 tasks'));assert(!h.includes('No tasks match'))});
test('Market command selects record on the same route',()=>{t.state.route='markets';t.state.query='coatings';click({commandMarket:'2'});assert.equal(t.state.activeMarket,2);assert.equal(t.state.query,'');assert(el('view').innerHTML.includes('Bioadhesives Market'))});
test('Category filter retains keyboard focus',()=>{t.state.route='home';t.state.category='all';t.state.briefFilter='all';const focused=node();focused.hasAttribute=k=>k==='data-category';focused.getAttribute=()=>'';ctx.document.activeElement=focused;let restored=false;el('[data-category=""]').focus=()=>{restored=true};const target=node();target.hasAttribute=k=>k==='data-category';target.value='Competitor';listeners.change({target});assert(restored);ctx.document.activeElement=null});
test('All five Studio versions are linked under Intelligence Studio',()=>{t.state.route='studio';const h=t.shell();for(const id of ['studio','studio-next','studio-v3','studio-v4','studio-v5'])assert(h.includes('href="#'+id+'"'));assert(h.includes('Intelligence Studio versions'))});
test('Every expressive Studio task retains its version route and subject',()=>{for(const base of ['studio-v3','studio-v4','studio-v5']){for(const task of t.S.tasks){ctx.location.hash='#'+base+'/'+task.id;t.route();assert.equal(t.state.route,base+'-workspace');assert(t.view().includes('href="#'+base+'"'))}t.state.route=base;t.openStudioTask('company-profile',{subject:'3M Company',context:'Positioning',origin:''});assert.equal(ctx.location.hash,'#'+base+'/company-profile');t.route();assert.equal(t.studioDraft().subject,'3M Company');assert.equal(t.studioDraft().context,'Positioning')}});
test('Guided Studio starts with a brief rather than the capability catalog',()=>{t.state.route='studio-next';t.studioNextState.stage='brief';const h=t.view();assert(h.includes('id="studio-next-form"'));assert(!h.includes('data-next-select='));assert(h.includes('Browse all capabilities'))});
test('Guided objective restricts choices while retaining original scopes',()=>{t.studioNextState.stage='choose';t.studioNextState.goal='competition';const h=t.studioNext();assert(h.includes('data-next-select="competitor-profile"'));assert(!h.includes('data-next-select="market-model"'));assert(h.includes('Company financials'))});
test('Guided directory searches original names and supports empty recovery',()=>{t.studioNextState.stage='browse';t.studioNextState.query='PESTLE';assert(t.studioNext().includes('data-next-select="pestle"'));t.studioNextState.query='zzzzzz';assert(t.studioNext().includes('No deliverables match'));t.studioNextState.query=''});
test('Guided preparation carries subject and stays on separate route',()=>{t.state.route='studio-next';t.studioNextState.subject='Industrial adhesives';click({nextPrepare:'competitor-profile'});assert.equal(ctx.location.hash,'#studio-next/competitor-profile');t.route();assert.equal(t.state.route,'studio-next-workspace');assert.equal(t.studioDraft().subject,'Industrial adhesives');assert(t.studioWorkspace().includes('href="#studio-next"'))});
test('Returning to a guided deliverable preserves context and template selection',()=>{t.studioDraft().context='Keep this priority';t.studioDraft().templateName='existing.xlsx';t.studioDraft().templateSelected=true;t.state.route='studio-next';click({nextPrepare:'competitor-profile'});t.route();assert.equal(t.studioDraft().context,'Keep this priority');assert.equal(t.studioDraft().templateName,'existing.xlsx');assert.equal(t.studioDraft().templateSelected,true)});
test('Every guided task deep link resolves without replacing original links',()=>{for(const task of t.S.tasks){ctx.location.hash='#studio-next/'+task.id;t.route();assert.equal(t.state.route,'studio-next-workspace');assert(t.view().includes(task.name.replace(/&/g,'&amp;')))}ctx.location.hash='#studio/market-model';t.route();assert.equal(t.state.route,'studio-workspace');t.studioNextState.stage='brief'});
test('Studio preserves all 22 existing capabilities and original mappings',()=>{assert.equal(t.S.tasks.length,22);const ids=new Set(t.S.tasks.map(x=>x.id));assert.equal(ids.size,22);for(const task of t.S.tasks){assert.equal(task.description,ctx.window.GROWTHIQ_DATA.agents[task.group][task.index].description)}});
test('Studio is a primary Intelligence navigation item',()=>{t.state.route='studio';const h=t.shell();assert(h.indexOf('href="#studio"')<h.indexOf('href="#ask"'));assert(h.indexOf('href="#studio"')<h.indexOf('<p class="nav-label">Explore'));assert(!h.includes('<span>Agents</span>'));assert(h.includes('aria-current="page"'))});
test('Studio objective and output filters combine',()=>{t.state.route='studio';t.state.query='';t.state.studioGoal='growth';t.state.studioFormat='Excel';const h=t.studio();assert(h.includes('2 tasks'));assert(h.includes('data-studio-task="market-data"'));assert(!h.includes('data-studio-task="swot"'))});
test('Studio search matches original capability names',()=>{t.state.studioGoal='all';t.state.studioFormat='all';t.state.query='PESTLE';const h=t.studio();assert(h.includes('1 task'));assert(h.includes('data-studio-task="pestle"'))});
test('Studio empty state offers filter recovery',()=>{t.state.query='zzzz';assert(t.studio().includes('data-studio-clear'));click({},['data-studio-clear']);assert.equal(t.state.query,'');assert.equal(t.state.studioGoal,'all')});
test('Every task deep link resolves to its own workspace',()=>{for(const task of t.S.tasks){ctx.location.hash='#studio/'+task.id;t.route();assert.equal(t.state.route,'studio-workspace');assert.equal(t.state.studioTask,task.id);const h=t.studioWorkspace();assert(h.includes(task.name.replaceAll('&','&amp;')));assert(!h.includes('undefined'));assert(h.includes('Scope outline based on the existing capability'))}});
test('Unknown Studio task recovers to catalog',()=>{ctx.location.hash='#studio/not-a-task';t.route();assert.equal(t.state.route,'studio')});
test('Market context carries existing figures into model brief',()=>{t.state.route='markets';click({studioTask:'market-model',studioMarket:'2'});assert.equal(t.state.studioTask,'market-model');assert.equal(t.studioDraft().subject,'Bioadhesives Market');assert(t.studioDraft().context.includes('8.6%'));assert(t.studioDraft().context.includes('USD 14.6 B'))});
test('Company context carries original company data into profile brief',()=>{click({studioTask:'company-profile',studioCompany:'0'});assert.equal(t.studioDraft().subject,'3M Company');assert(t.studioDraft().context.includes('Solventum'))});
test('Signal strategy brief uses captured title and relevance',()=>{click({studioTask:'strategy-brief',studioSignal:'2'});assert(t.studioDraft().subject.includes('Sika'));assert(t.studioDraft().context.includes('H.B. Fuller'))});
test('Blank Studio brief shows an accessible error',()=>{el('studio-subject').value=' ';el('studio-context').value='';t.reviewStudioBrief();assert.equal(t.state.studioStep,'brief');assert.equal(el('studio-subject-error').hidden,false)});
test('Review uses user brief without generating research',()=>{el('studio-subject').value='Assess Sika expansion';el('studio-context').value='Use the Turkish market context.';t.reviewStudioBrief();assert.equal(t.state.studioStep,'review');const h=t.studioWorkspace();assert(h.includes('Assess Sika expansion'));assert(h.includes('Generation is not connected here'));assert(h.includes('data-studio-export'))});
test('Draft save persists text but not template contents',()=>{t.persistStudioDraft();const saved=JSON.parse(store['growthiq-studio-drafts']);assert.equal(saved['strategy-brief'].subject,'Assess Sika expansion');assert(!('templateSelected' in saved['strategy-brief']));assert(t.studio().includes('22 tasks'))});
test('Template brief requires an actual file selection before review',()=>{t.openStudioTask('market-data');el('studio-subject').value='Adhesives';el('studio-context').value='';t.reviewStudioBrief();assert.equal(t.state.studioStep,'brief');assert.equal(el('studio-template-error').hidden,false);t.studioDraft().templateSelected=true;t.studioDraft().templateName='market.xlsx';t.reviewStudioBrief();assert.equal(t.state.studioStep,'review');assert(t.studioWorkspace().includes('market.xlsx'))});
test('Task brief escapes HTML in user input',()=>{t.studioDraft().subject='<script>alert(1)</script>';const h=t.studioWorkspace();assert(!h.includes('<script>'));assert(h.includes('&lt;script&gt;'))});
test('Global search includes deep research tasks with original identity',()=>{t.commandResults('Whitepaper');assert(el('command-results').innerHTML.includes('data-command-agent="deep:12"'))});
test('Saved draft restores persisted text after another contextual brief',()=>{t.openStudioTask('market-model',{subject:'Saved market A',context:'Original context',origin:'Market explorer'});t.persistStudioDraft();t.openStudioTask('market-model',{subject:'New market B',context:'Different context',origin:'Market explorer'});assert.equal(t.studioDraft().subject,'New market B');click({studioResume:'market-model'});assert.equal(t.studioDraft().subject,'Saved market A');assert.equal(t.studioDraft().context,'Original context')});
test('Restored template draft requires file reselection',()=>{t.state.studioDrafts['market-data']={subject:'Template test',context:'',templateName:'original.xlsx'};click({studioResume:'market-data'});assert.equal(t.studioDraft().templateName,'original.xlsx');assert.equal(t.studioDraft().templateSelected,false)});
test('Three themes apply to the entire document and persist',()=>{assert.equal(ctx.window.GROWTHIQ_THEMES.choices.length,3);for(const theme of ctx.window.GROWTHIQ_THEMES.choices){ctx.window.GROWTHIQ_THEMES.apply(theme.id);assert.equal(ctx.document.documentElement.dataset.theme,theme.id);assert.equal(store['growthiq-colour-theme'],theme.id);t.state.route='studio';const h=t.shell();assert(h.includes('value="'+theme.id+'" selected'));assert(h.includes('aria-label="Colour theme"'))}});
test('Theme switching preserves task draft and route',()=>{t.state.route='studio-workspace';t.studioDraft().subject='Keep my research';const task=t.state.studioTask;ctx.window.GROWTHIQ_THEMES.apply('precision');assert.equal(t.state.route,'studio-workspace');assert.equal(t.state.studioTask,task);assert.equal(t.studioDraft().subject,'Keep my research')});
test('Invalid persisted theme falls back to Advisory',()=>{ctx.window.GROWTHIQ_THEMES.apply('unknown');assert.equal(ctx.document.documentElement.dataset.theme,'advisory')});
test('Theme select change announces selected palette',()=>{const target=node();target.hasAttribute=k=>k==='data-theme-select';target.value='precision';listeners.change({target});assert.equal(ctx.document.documentElement.dataset.theme,'precision');assert(el('theme-status').textContent.includes('Precision theme selected'))});

function reloadTheme(saved,url='http://127.0.0.1:8770/',blocked=false,savedHeader='light'){
 const values={'growthiq-colour-theme':saved,'growthiq-header-style':savedHeader};
 const c={URL,location:{href:url},window:{},document:{documentElement:{dataset:{}},querySelectorAll:()=>[],querySelector:()=>null,addEventListener(){}},localStorage:{getItem:k=>{if(blocked)throw Error('blocked');return values[k]},setItem:(k,v)=>{if(blocked)throw Error('blocked');values[k]=v}}};
 c.window.history={state:null,replaceState:(_state,_title,url)=>{c.location.href=url}};
 vm.createContext(c);vm.runInContext(fs.readFileSync(root+'/theme.js','utf8'),c);return {c,values};
}
test('Retired palette selections migrate to Advisory on reload',()=>{for(const retired of ["grove", "midnight", "evergreen", "graphite", "slate", "atelier", "parchment"])assert.equal(reloadTheme(retired).c.document.documentElement.dataset.theme,'advisory')});
test('Retained palette restores before app initialization',()=>{assert.equal(reloadTheme('mineral').c.document.documentElement.dataset.theme,'mineral')});
test('Theme comparison links open and persist the requested palette',()=>{const {c,values}=reloadTheme('mineral','http://127.0.0.1:8770/?theme=advisory#studio');assert.equal(c.document.documentElement.dataset.theme,'advisory');assert.equal(values['growthiq-colour-theme'],'advisory');assert.equal(c.location.href,'http://127.0.0.1:8770/#studio');c.window.GROWTHIQ_THEMES.apply('precision');assert.equal(reloadTheme(values['growthiq-colour-theme'],c.location.href).c.document.documentElement.dataset.theme,'precision');assert.equal(reloadTheme('mineral','http://127.0.0.1:8770/?theme=invalid').c.document.documentElement.dataset.theme,'mineral')});
test('Unavailable storage does not prevent theme selection',()=>{const {c}=reloadTheme(null,undefined,true);assert.equal(c.document.documentElement.dataset.theme,'advisory');c.window.GROWTHIQ_THEMES.apply('precision');assert.equal(c.document.documentElement.dataset.theme,'precision')});

test('Only the three shortlisted themes appear in preferred order',()=>{t.state.route='ask';const h=t.shell();assert(!h.includes('<optgroup'));assert.deepEqual(Array.from(ctx.window.GROWTHIQ_THEMES.choices,t=>t.id),['precision','advisory','mineral']);for(const theme of ['precision','advisory','mineral']){const {c}=reloadTheme(null,'http://127.0.0.1:8770/?theme='+theme+'#ask');assert.equal(c.document.documentElement.dataset.theme,theme)}});

test('Dark header toggles accessibly without resetting current work',()=>{t.state.route='studio-workspace';t.studioDraft().subject='Preserve header trial';ctx.window.GROWTHIQ_THEMES.applyHeader('light');click({},['data-header-toggle']);assert.equal(ctx.document.documentElement.dataset.header,'dark');assert.equal(store['growthiq-header-style'],'dark');assert(t.shell().includes('aria-label="Dark header" aria-pressed="true"'));assert.equal(t.state.route,'studio-workspace');assert.equal(t.studioDraft().subject,'Preserve header trial');assert(el('theme-status').textContent.includes('Dark header enabled'));click({},['data-header-toggle']);assert.equal(ctx.document.documentElement.dataset.header,'light')});
test('Header preference persists independently of all three themes',()=>{ctx.window.GROWTHIQ_THEMES.applyHeader('dark');for(const theme of ['precision','advisory','mineral']){ctx.window.GROWTHIQ_THEMES.apply(theme);assert.equal(ctx.document.documentElement.dataset.header,'dark');const {c}=reloadTheme(theme,undefined,false,'dark');assert.equal(c.document.documentElement.dataset.header,'dark');assert.equal(c.document.documentElement.dataset.theme,theme)}});
test('Header comparison links consume both preferences and preserve page',()=>{const {c,values}=reloadTheme('mineral','http://127.0.0.1:8770/?v=header&theme=precision&header=dark#home');assert.equal(c.document.documentElement.dataset.header,'dark');assert.equal(c.document.documentElement.dataset.theme,'precision');assert.equal(values['growthiq-header-style'],'dark');assert.equal(c.location.href,'http://127.0.0.1:8770/?v=header#home');c.window.GROWTHIQ_THEMES.applyHeader('light');assert.equal(reloadTheme(values['growthiq-colour-theme'],c.location.href,false,values['growthiq-header-style']).c.document.documentElement.dataset.header,'light')});
test('Invalid or unavailable header storage safely defaults to light',()=>{assert.equal(reloadTheme('precision',undefined,false,'invalid').c.document.documentElement.dataset.header,'light');const {c}=reloadTheme('precision',undefined,true);c.window.GROWTHIQ_THEMES.applyHeader('dark');assert.equal(c.document.documentElement.dataset.header,'dark')});

fs.writeFileSync(root+'/verification/results.json',JSON.stringify({scope:'Local JavaScript function and event-handler checks with a mocked DOM. Not browser or visual verification.',checks:results},null,2));console.log(JSON.stringify({passed:results.length,checks:results.map(r=>r.name)},null,2));
